# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - commongroundstest

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test (in ./server directory)
        working-directory: ./server
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          # fail_ci_if_error: true # optional (default = false)
          flags: unittests # optional
          # name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)

      - name: Zip artifact for deployment
        run: Compress-Archive -Path ./* -DestinationPath release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E7DEFF92714042DA93868B3E0102C1F8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_294AA45731FF4F3BA06DEF468268918E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9DE1EDFBC1B343658A8AA01D68561C58 }}

      - name: Deploy to Azure Web App using Zip Deploy
        run: |
          az webapp deployment source config-zip \
            --resource-group property-management-app_group \
            --name commongroundstest \
            --src release.zip

      - name: Display Deployment URL
        run: echo "Your app is deployed at https://commongroundstest.azurewebsites.net"